erDiagram
    GitRepo }o--o{ Cluster : "uses"
    GitRepo }o--o{ ClusterGroup : "uses"
    GitRepo ||--o{ Bundle : "creates"
    ClusterGroup }o--o{ Cluster : "uses"
    Bundle ||--o{ BundleDeployment : "results in"
    BundleDeployment ||--o{ Resource : "creates"
