flowchart LR
    GR1(GitRepo Resource)
    GR2(GitRepo Resource)
    GR3(GitRepo Resource)
    C(Cluster)

    C --> GR1
    C --> GR2
    C --> GR3

    GR1 --> BD1(Bundle 1)
    GR1 --> BD2(Bundle 2)
    GR2 --> BD3(Bundle 3)
    GR3 --> BD4(Bundle 4)
    GR3 --> BD5(Bundle 5)

    BDD1(BundleDeployment 1)
    BDD2(BundleDeployment 2)
    BDD3(BundleDeployment 3)
    BDD4(BundleDeployment 4)
    BDD5(BundleDeployment 5)
    BDD6(BundleDeployment 6)
    BDD7(BundleDeployment 7)
    BDD8(BundleDeployment 8)

    BD1 --> BDD1
    BD1 --> BDD2
    BD2 --> BDD3
    BD2 --> BDD4
    BD3 --> BDD5
    BD3 --> BDD6
    BD4 --> BDD7
    BD5 --> BDD8


