flowchart LR
    GR1(GitRepo Resource)
    GR2(GitRepo Resource)
    GR3(GitRepo Resource)
    GR4(GitRepo Resource)
    GR5(GitRepo Resource)
    C1(Cluster 1)
    C2(Cluster 2)
    CG(ClusterGroup)

    C1 --> GR1
    C1 --> GR2
    C1 --> GR3
    C2 --> GR4
    C2 --> GR5

    GR1 --> BD1(Bundle 1)
    GR1 --> BD2(Bundle 2)
    GR2 --> BD3(Bundle 3)
    GR3--> BD4(Bundle 4)
    GR3--> BD5(Bundle 5)
    GR4--> BD6(Bundle 6)
    GR4--> BD7(Bundle 7)
    GR5--> BD8(Bundle 8)

    CG --> C1
    CG --> C2

    BDD1(BundleDeployment 1)
    BDD2(BundleDeployment 2)
    BDD3(BundleDeployment 3)
    BDD4(BundleDeployment 4)
    BDD5(BundleDeployment 5)
    BDD6(BundleDeployment 6)
    BDD7(BundleDeployment 7)
    BDD8(BundleDeployment 8)
    BDD9(BundleDeployment 9)
    BDD10(BundleDeployment 10)
    BDD11(BundleDeployment 11)
    BDD12(BundleDeployment 12)

    BD1 --> BDD1
    BD1 --> BDD2
    BD2 --> BDD3
    BD2 --> BDD4
    BD3 --> BDD5
    BD3 --> BDD6
    BD4 --> BDD7
    BD5 --> BDD8
    BD6 --> BDD9
    BD6 --> BDD10
    BD7 --> BDD11
    BD8 --> BDD12

